export interface GalleryItem {
  id: string;
  imageSrc: string;
  alt: string;
  category: "Marine & Dredging" | "Civil & Structural" | "Pipeline & Energy" | "Fleet & Equipment";
  title?: string;
  description?: string;
  location?: string;
  equipmentUsed?: string[];
  isFeatured?: boolean;
}

export const GALLERY_PAGE_DATA = {
  hero: {
    badge: "Field Operations & Fleet Proof",
    title: "Engineering Excellence In Action",
    subtitle:
      "A visual portfolio of heavy asset deployments, marine engineering projects, and civil infrastructure executions across Nigeria.",
  },
  items: [ 
    
    {
      id: "gal-01",
      imageSrc: "/images/gallery/imgs/pel1.jpg",
      alt: "",
      category: "Marine & Dredging",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-02",
      imageSrc: "/images/gallery/imgs/pel2.jpg",
      alt: "",
      category: "Pipeline & Energy",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-03",
      imageSrc: "/images/gallery/imgs/pel3.jpg",
      alt: "",
      category: "Civil & Structural",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-04",
      imageSrc: "/images/gallery/imgs/pel4.jpg",
      alt: "",
      category: "Civil & Structural",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-05",
      imageSrc: "/images/gallery/imgs/pel5.jpg",
      alt: "",
      category: "Pipeline & Energy",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-06",
      imageSrc: "/images/gallery/imgs/pel6.jpg",
      alt: "",
      category: "Pipeline & Energy",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-07",
      imageSrc: "/images/gallery/imgs/pel7.jpg",
      alt: "",
      category: "Civil & Structural",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-08",
      imageSrc: "/images/gallery/imgs/pel8.jpg",
      alt: "",
      category: "Civil & Structural",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-09",
      imageSrc: "/images/gallery/imgs/pel9.jpg",
      alt: "",
      category: "Marine & Dredging",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-10",
      imageSrc: "/images/gallery/imgs/pel10.jpg",
      alt: "",
      category: "Fleet & Equipment",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-11",
      imageSrc: "/images/gallery/imgs/pel11.jpg",
      alt: "",
      category: "Marine & Dredging",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },
    {
      id: "gal-12",
      imageSrc: "/images/gallery/imgs/pel12.jpg",
      alt: "",
      category: "Fleet & Equipment",
      title: "",
      description: "",
      location: "",
      equipmentUsed: [],
      isFeatured: true,
    },

    /*
    {
      id: "gal-01",
      imageSrc: "/images/gallery/imgs/pel-works-img(1).jpg",
      alt: "Cutter Suction Dredger operating in riverine channel",
      category: "Marine & Dredging",
      title: "Navigation Channel Capital Dredging",
      description: "Channel deepening and sediment removal using high-capacity cutter suction spreads.",
      location: "Niger Delta, Nigeria",
      equipmentUsed: ["Cutter Suction Dredger", "Varisco Dewatering Pump"],
      isFeatured: true,
    },
    {
      id: "gal-02",
      imageSrc: "/images/gallery/imgs/swamp-excavator-01.jpg",
      alt: "WILCO Amphibious Swamp Excavator in marshland",
      category: "Fleet & Equipment",
      location: "Rivers State",
      equipmentUsed: ["WILCO Swamp Excavator"],
    },
    {
      id: "gal-03",
      imageSrc: "/images/gallery/imgs/piling-shoreline.jpg",
      alt: "Sheet piling installation for shoreline protection",
      category: "Marine & Dredging",
      title: "Coastal Revetment & Sheet Piling",
      description: "Heavy structural piling to stabilize riverbanks against extreme tidal erosion.",
      location: "Bonny Island, Nigeria",
      equipmentUsed: ["GROVE Crane 30t", "CAT 325CL Excavator"],
      isFeatured: true,
    },
    {
      id: "gal-04",
      imageSrc: "/images/gallery/imgs/pipeline-trenching.jpg",
      alt: "Cross country swamp flowline laying",
      category: "Pipeline & Energy",
      title: "Swamp Flowline Fabrication",
      equipmentUsed: ["CAT D6R Bulldozer", "INGERSOLL RAND 750 Compressor"],
    },
    {
      id: "gal-05",
      imageSrc: "/images/gallery/imgs/cat-fleet-lineup.jpg",
      alt: "Heavy Equipment Fleet array in yard",
      category: "Fleet & Equipment",
      title: "PEL Heavy Fleet Staging Yard",
      description: "Pre-mobilization mechanical inspection and safety compliance audits for CAT equipment.",
      isFeatured: true,
    },
    */
  ] as GalleryItem[],
};